### ISSUE TITLE
Ask for licence prices

### ISSUE THREAD

**Issue by wangchenghuidream** [ccdc-opensource/csd-python-api-scripts#34]
How do I get a licence, I can't submit information through the link in the readme. if i only install csd-python-api by pip install csd-python-api, How do I activate it?

**Comment by Alex-AMC** [comment]
When you say link in the readme are you referring to the [support@ccdc.cam.ac.uk](mailto:support@ccdc.cam.ac.uk)? If not, please email them to help you out with the licence.  They will also be able to help you activate your licence and your python API install :)

**Comment by Alex-AMC** [comment]
Or if you are referring to : 
> Don’t have a licence? Contact us [here to request a quote or demonstration.](https://www.ccdc.cam.ac.uk/theccdcprofile/contactus/) 

Which part can you not submit information through?
