### ISSUE TITLE
Pull request for Multi Component Hydrogen Bond Propensity (MHBP)

### ISSUE THREAD

**Issue by Luke2Sky** [ccdc-opensource/csd-python-api-scripts#43]
I made some changes to the MHBP script that I think would be useful for other people. How do I contribute? I already have a fork of this repository with the changes in a branch with my name. Should I create a new MHBP file, or should I just do a Pull request with the modified MHBP? I never contributed to an open source project before, is there something more I should know before doing a pull request?

**Comment by Alex-AMC** [comment]
Hey @Luke2Sky, thanks for raising this. A PR is the correct mechanism for adding improvements to the scripts. Once a couple of us have had the chance to review the changes we can get them merged into the repository. 

I am going to close this issue and carry on any conversation on the #44 PR itself.
