### ISSUE TITLE
Problem with the default CCDC coformers library

### ISSUE THREAD

**Issue by Luke2Sky** [ccdc-opensource/csd-python-api-scripts#50]
I am reporting this here instead of trying and merging my fix because I don't know if the directory structure is different in windows. But in linux, this snippet in Multi-Component Hydrogen Bond propensity  is wrong: 
```python
    # Set up the necessary arguments to run the script
    # For CSD 2023.1
    ccdc_coformers_dir = os.path.join(
        io.csd_directory(),
        os.pardir, os.pardir,
        'ccdc-software',
        'mercury',
        'molecular_libraries',
        'ccdc_coformers')
```
The double os.pardir results in it are leaving outside the CCDC suite directory in linux. I also use a custom installation folder, so it could be due to that.

**Comment by pmbulit** [comment]
A fix for this will be in the next release and it should be OS agnostic. The coformers library will be included with the API install so the paths will change. If you make any other changes and want to merge them just keep this block as it is when you do a PR
