### ISSUE TITLE
Mismatch on coordinates tranformation

### ISSUE THREAD

**Issue by chao1224** [ccdc-opensource/csd-python-api-scripts#54]
Hi there, I found an issue with the mismatch in the transformation between orthogonal coordinates and fractional coordinates.
- If I take `AABHTZ` as an example.
- By following the [Molecule class and Atom class API](https://downloads.ccdc.cam.ac.uk/documentation/API/modules/molecule_api.html), I can have the following positions for two Cl atoms:
```
Orthogonal coordinates
-3.6720,  0.7941,  0.7034
-6.1654, -3.8433,  2.1679

Fractional coordinates
-0.3355,  0.0998,  0.1061
-0.6407, -0.3084,  0.3270
```

- However, if I take the lattice from the [Crystal class API](https://downloads.ccdc.cam.ac.uk/documentation/API/modules/crystal_api.html#ccdc.crystal.Crystal), I have the following calculated fractional coordinates:
```
Calculated fractional coordinates
-0.34111226  0.08164345  0.30322527
-0.57436619 -0.39512845  0.40525461
```

May I ask if I missed anything or if there are bugs in the codeds? Any help is appreciated.

-----
BTW. I am using the following pytorch codes for the `Calculated fractional coordinates`:
```
inverse_lattice = torch.tensor(np.linalg.inv(lattice.matrix), dtype=torch.float32)
fractional_coords = torch.einsum("bi,ij->bj", orthogonal_coords, inverse_lattice)
```

**Comment by Alex-AMC** [comment]
Hi @chao1224, 

Thank you for raising this. Could you please provide the content of the `lattice.matrix` variable, as that property doesn't exist within the CSD Python API so I am curious as to what the ortho-frac transformation matrix looks like. We do provide the ability to access the orhotogonal to fractional transformation matrix in `crystal.orthogonal_to_fractional`.

Could you try using the following snippet of code and see if you get the same mismatch: 
```python 
crystal = CrystalReader('CSD').crystal('AABHTZ')
atom_1 = crystal.molecule.atoms[0]
ortho_coordinates =  np.array([*atom_1.coordinates])
frac_coordinates = np.array([*atom_1.fractional_coordinates])
matrix  = np.array(crystal.orthogonal_to_fractional.rotation)
new_frac_coordinates = np.einsum("bi,ij->bj", np.array([ortho_coordinates]), matrix)
print(f"Stored Fractional: {frac_coordinates}")
print(f"Calculated Fractional: {new_frac_coordinates[0]}") 
```

**Comment by Alex-AMC** [comment]
Marked the issue as closed as no problems were found with the coordinates from the API.
