### ISSUE TITLE
Doubts about new changes

### ISSUE THREAD

**Issue by Luke2Sky** [ccdc-opensource/csd-python-api-scripts#62]
I made multi-component HBP totally non-deterministic and made a naive but functional parallelization of the code. Improvements would be to try and make each process use some amount of threads (I would have to perform tests to optimize the amount) as the HBP is heavily I/O dependent and therefore is not actively using heavy processing most of the time (Instruction level pipelining would probably be beneficial and would not have to circumvent the GIL for each subprocess. Creating more processes than processors is not ideal as it circumvents this problem, but can use absurd amounts of memory because each subprocess copies every object to its memory). My doubt is if I should create another script in the PR, or if I should use the same script (the new script would have some parts identical to the old one). The behavior is the same as before if no --jobs is specified. If --jobs -1 it uses the default of using the maximum amount of processors available. Furthermore, could I include my name in the script along with the original credits? As I think this, with the other changes and the addition of more try-excepts as I said would be added in the other issue are significant enough to do so.

**Comment by pmbulit** [comment]
It would probably be better to have it as a separate script, but without seeing the code is hard to decide. If you make a PR I can have a look and we can decide how to move forward
