### ISSUE TITLE
Architecture of the API

### ISSUE THREAD

**Issue by Luke2Sky** [ccdc-opensource/csd-python-api-scripts#66]
Hello, while trying to profile and compare my parallelization of the code for MCHBP, I came to the realization that sometimes the default normal code seems to use ~ 37% of my 8 threads CPU. The problem is that the GIL only allows for you to use 12.5%, as it seems to respect virtual cores.  So, it is probably using between 2-3 cores on the API itself, that seems to be written in  C++ (I got serialization mistakes typical to C++ objects).
 I am testing improving it further, but I had some problems in the older version because sometimes R processes were ran at the same time and it was very slow, as they use all cores and had to compete with various processes running MCHBP and logistic_regression.R. 
My question is, is there a way to set up how many cores are used? I couldn't find anything in the API documentation. It didn't say anything about using multiple cores on the generation of the fitting data. On my analysis, it seems to be using less cores than possible. This is further proved by the fact that when using multiprocessing (Joblib) it is possible to at least get a 2x improve in speed.

**Comment by Alex-AMC** [comment]
Hello @Luke2Sky, 

Thank you for getting in touch about this. Yes, as you rightly point out, the HBP components get passed over to C++, which then uses the R model to train it. 
Currently, there is no direct method for setting the number of cores being used, but I will feed this back as a desired feature for the model. 

Parallelization with Python on an API that runs C++ and R is a very tricky task, as you have discovered with serialisation of C++ objects. I've found in the past that using spawns to run chunks of tasks in Python the path of least resistance/smallest headaches with race conditions. 

I'll reach out to some of the C++/R Devs to see if there any easy wins here, but to answer the original question, there is no way of to adjust the numbers of CPUs used through the API at the moment.

**Comment by Luke2Sky** [comment]
I solved the serialization issues by avoiding passing objects through processes. It is working mostly fine. But I think the control on the API would be the best approach as it would avoid messaging overhead. Also, spawning new processes is not that good in my understanding, as it has to partially put the sqlite database in memory, which feels expensive. As the sqlite database is handled by the API I could not serialize and use a pool of already loaded instances of it. Also, the overhead is even lower because sqlite3 allows for concurrent read access to the same database in memory on C++.
